pspEnabled: false

config:
  modules:
    http_2xx_get:
      prober: http
      timeout: 5s
      http:
        valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
        valid_status_codes:
        - 200
        - 204
        method: GET
        follow_redirects: true
#        fail_if_not_ssl: true
        preferred_ip_protocol: "ip4"
    http_k8s_get:
      prober: http
      timeout: 3s
      http:
        valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
        valid_status_codes:
        - 200
        - 204
        method: GET
        follow_redirects: true
#        fail_if_not_ssl: true
        preferred_ip_protocol: "ip4"
